project_name: flyte
builds:
  - skip: true
release:
  github:
    owner: evalsocket
    name: flyte
  draft: false
  prerelease: auto
  discussion_category_name: General
  name_template: "Flyte v{{.Version}} milestone release"
  disable: false
  extra_files:
    - glob: ./release/*