name: Manually push

on:
  workflow_dispatch:
    inputs:
      flyte_version:
        description: 'flyte version'
        required: true
        default: 'latest'
        type: string

jobs:
  sandbox-lite-build-dind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Set flyte version to release
        id: set_version
        run: |
          echo ::set-output name=flyte_version::$(echo ${{ github.event.inputs.flyte_version }})
      - name: Prepare DIND Image Names
        id: dind-names
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/flyte-sandbox-lite
          tags: |
            ${{ steps.set_version.outputs.flyte_version }}
            type=sha,format=long
      - name: Prepare Sandbox images
        run: |
          make -C docker/sandbox-lite bootstrap
          make -C docker/sandbox-lite images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: "${{ secrets.FLYTE_BOT_USERNAME }}"
          password: "${{ secrets.FLYTE_BOT_PAT }}"
      - name: Build and push DIND Image
        uses: docker/build-push-action@v2
        with:
          context: docker/sandbox-lite
          platforms: linux/arm64, linux/amd64
          push: true
          target: dind
          tags: ${{ steps.dind-names.outputs.tags }}
          file: docker/sandbox-lite/images/dockerfiles/k3s/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
